// The schema-version-1 session envelope, as the unmodified Flask routes
// return it, limited to the fields this slice reads.
//
// These types are hand-written.  `src/contract/samples.ts` assigns envelopes
// generated by the Python server to them, so a field that Python renames,
// removes or retypes fails `npm run check` (experiment S11).
//
// `id` and `hash` are opaque strings.  Nothing in this slice converts one to
// a number.  Enumerated values (`state`, `disposition`, `action`, `verdict`)
// are typed `string` because that is what the wire carries; the view maps
// the known values and shows an unknown one as it arrived.

export interface Envelope {
  schema_version: number;
  state: string;
  report_revision: number;
  verdict_revision: number;
  fingerprint: string | null;
  snapshot: Snapshot | null;
  verdicts: VerdictEntry[];
  override_status: OverrideStatusEntry[];
}

export interface VerdictEntry {
  id: string;
  verdict: string;
}

export interface OverrideStatusEntry {
  id: string;
  status: string;
}

export interface Snapshot {
  sections: Section[];
}

export interface Section {
  kind: string;
  decisions: Decision[];
  armor?: ArmorSection;
}

/** One proposal in the section.  The server decides which items have one. */
export interface Decision {
  id: string;
  hash: string;
  action: string;
  reason: string;
}

export interface ArmorSection {
  exact_duplicate_groups: ExactGroup[];
  same_stat_groups: SameStatGroup[];
}

export interface GroupBase {
  group_kind: string;
  group_id: string;
  hash: string;
  name: string;
  type: string;
  guardian_class: string;
  item_archetype: string;
  tier: number | null;
  stats: Record<string, number>;
  spirit_signature: string[];
}

export interface ExactGroup extends GroupBase {
  tuning_mod_slot: string;
  seasonal_mod: string;
  holofoil: string;
  preferred_survivor_id: string;
  members: ExactMember[];
}

export interface SameStatGroup extends GroupBase {
  members: SameStatMember[];
}

export interface MemberBase {
  id: string;
  location: string;
  protection_level: string | null;
  protection_reason: string;
  equipped: boolean;
  in_loadout: boolean;
  locked: boolean;
  masterwork_tier: number | null;
  power: number | null;
  proposal_action: string | null;
  proposal_reason: string | null;
}

export interface ExactMember extends MemberBase {
  disposition: string;
}

export interface SameStatMember extends MemberBase {
  tuning_stat: string;
  tuning_mod_slot: string;
  seasonal_mod: string;
  holofoil: string;
  selected_partner_id: string | null;
}

export type Member = ExactMember | SameStatMember;

/** The one runtime check: enough to refuse a response that is not ours. */
export function isEnvelope(value: unknown): value is Envelope {
  if (typeof value !== 'object' || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    candidate.schema_version === 1 &&
    typeof candidate.state === 'string' &&
    Number.isInteger(candidate.report_revision) &&
    Number.isInteger(candidate.verdict_revision) &&
    Array.isArray(candidate.verdicts) &&
    Array.isArray(candidate.override_status) &&
    (candidate.snapshot === null ||
      (typeof candidate.snapshot === 'object' &&
        Array.isArray((candidate.snapshot as Record<string, unknown>).sections)))
  );
}
